### ISSUE TITLE
4 panels FigureMaker on directory issue

### ISSUE THREAD

**Issue by alexcarisey** [quantixed/imagej-macros#13]
Hi Stephen, something is not working for me in Montage_Horizontal_RGB_on_Directory.ijm. When I run it on a folder of 3 color stacks in order to create 3+1 merged panel montages, it stops at line 105 because it's looking for the 4th panel but cannot find any (original stack has 3 slices). I believe that it's because the merged panel hasn't yet been generated yet.

If you add the following lines right [before line 98](https://github.com/quantixed/imagej-macros/blob/1ac8964e2fc8e43ac04de279af244b6a77ddf0ce/Figure%20Maker/Montage_Horizontal_RGB_on_Directory.ijm#L98), it now works for me:
`mergeString = "c1=[C1-" + tifflist[i] + "] c2=[C2-" + tifflist[i] + "] c3=[C3-" + tifflist[i] + "] keep";`
`run("Merge Channels...", mergeString);`
`rename("merge");`

Although you still don't have the flexibility of color choice, frame selection, etc that you've successfully implemented in the "flexible" versions of this script.
I'm only using GitHub as a repo for my stuff, I'm not used to the fork/issue/report thingy so please let me know if I'm doing this wrong!

And thank you very much for this script, it's amazing! Following your great example, I'm implementing a way to go from .nd (MetaMorph files) to the source material for your script with correct intensity adjustments handling across many files and conditions.

**Comment by quantixed** [comment]
Hi Alex, Thanks for raising the issue and for the suggested fix! Actually, the script is written to only work on a directory of single RGB images. I just tested it and it sill works for this purpose (entirely possible that I broke it since I have updated a few other things but left this script alone). The problem is it doesn't work for 3 colour stacks. Adding those lines allows that montage but breaks the single RGB montage. Hmmm. Probably I need to write a directory version of the 'Flexible' montage maker, since this handles both types (I think).

**Comment by alexcarisey** [comment]
Oh gosh, I'm so sorry, I didn't pay enough attention to the title of the macro obviously! It does indeed work perfectly for the job advertised. I'll tweak it to make it serve my odd workflow.
Thank you again for this super handy script!
